openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /user:
    post:
      operationId: UserController_create
      summary: Create user
      description: Creates a new user
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: The user has been created
          content:
            application/json:
              example:
                id: b1b73593-2445-421a-af42-359114d6c536
                login: string
                role: admin
                createdAt: 1775287579998
                updatedAt: 1775287579998
        '400':
          description: Bad request. Body does not contain required fields
      tags:
        - Users
    get:
      operationId: UserController_findAll
      summary: Get all users
      description: Gets all users. Supports pagination and sorting
      parameters:
        - name: page
          required: false
          in: query
          description: Page number (starting from 1)
          schema:
            example: 1
            type: number
        - name: limit
          required: false
          in: query
          description: Number of items per page
          schema:
            example: 10
            type: number
        - name: sortBy
          required: false
          in: query
          description: The field to sort by
          schema:
            example: login
            enum:
              - id
              - login
              - role
              - createdAt
              - updatedAt
            type: string
        - name: order
          required: false
          in: query
          description: Sorting direction
          schema:
            example: DESC
            enum:
              - ASC
              - DESC
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              examples:
                Without pagination:
                  value:
                    - id: b1b73593-2445-421a-af42-359114d6c536
                      login: string
                      role: admin
                      createdAt: 1775287579998
                      updatedAt: 1775287579998
                  description: Without page and limit query parameters
                With pagination:
                  value:
                    total: 1
                    page: 1
                    limit: 10
                    data:
                      - id: b1b73593-2445-421a-af42-359114d6c536
                        login: string
                        role: admin
                        createdAt: 1775287579998
                        updatedAt: 1775287579998
                  description: With page and limit query parameters
        '400':
          description: Bad request. Wrong query parameters (hacker scope)
      tags:
        - Users
  /user/{id}:
    get:
      operationId: UserController_findOne
      summary: Get single user by id
      description: Get single user by id
      parameters:
        - name: id
          required: true
          in: path
          description: User id, format UUID v4
          schema: {}
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                id: b1b73593-2445-421a-af42-359114d6c536
                login: string
                role: admin
                createdAt: 1775287579998
                updatedAt: 1775287579998
        '400':
          description: Bad request. User id is invalid (not uuid)
        '404':
          description: User not found
      tags:
        - Users
    put:
      operationId: UserController_update
      summary: Update a user's password
      description: Updates a user's password by ID
      parameters:
        - name: id
          required: true
          in: path
          description: User id, format UUID v4
          schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordDto'
      responses:
        '200':
          description: The user has been updated
          content:
            application/json:
              example:
                id: b1b73593-2445-421a-af42-359114d6c536
                login: string
                role: admin
                createdAt: 1775287579998
                updatedAt: 1775288465881
        '400':
          description: Bad request. User id is invalid (not uuid)
        '403':
          description: oldPassword is wrong
        '404':
          description: User not found
      tags:
        - Users
    delete:
      operationId: UserController_remove
      summary: Deletes user
      description: >-
        Deletes user by ID. Sets authorId to null on articles, deletes user's
        comments
      parameters:
        - name: id
          required: true
          in: path
          description: User id, format UUID v4
          schema: {}
      responses:
        '204':
          description: The user has been deleted
          example: ''
        '400':
          description: Bad request. User id is invalid (not uuid)
        '404':
          description: User not found
      tags:
        - Users
  /article:
    post:
      operationId: ArticleController_create
      summary: Create article
      description: Creates a new article
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateArticleDto'
      responses:
        '201':
          description: The article has been created
          content:
            application/json:
              example:
                id: 0e2f864e-8611-4e41-9d49-1c94b1df5c95
                title: string
                content: string
                status: draft
                authorId: b1b73593-2445-421a-af42-359114d6c536
                categoryId: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                tags:
                  - nestjs
                  - typescript
                  - backend
                createdAt: 1775299578964
                updatedAt: 1775299578964
        '400':
          description: Bad request. Body does not contain required fields
      tags:
        - Articles
    get:
      operationId: ArticleController_findAll
      summary: Get all articles
      description: >-
        Gets all articles. Supports filtering by status, categoryId, and tag,
        pagination and sorting
      parameters:
        - name: page
          required: false
          in: query
          description: Page number (starting from 1)
          schema:
            example: 1
            type: number
        - name: limit
          required: false
          in: query
          description: Number of items per page
          schema:
            example: 10
            type: number
        - name: status
          required: false
          in: query
          description: Filter by article status
          schema:
            example: draft
            enum:
              - draft
              - published
              - archived
            type: string
        - name: categoryId
          required: false
          in: query
          description: Filter by categoryId
          schema:
            example: f3d2f4c6-5376-48df-b4a7-9fe825559db9
            type: string
        - name: tag
          required: false
          in: query
          description: Filter by tag
          schema:
            example: string
            type: string
        - name: sortBy
          required: false
          in: query
          description: The field to sort by
          schema:
            example: title
            enum:
              - id
              - title
              - content
              - status
              - authorId
              - categoryId
              - createdAt
              - updatedAt
            type: string
        - name: order
          required: false
          in: query
          description: Sorting direction
          schema:
            example: DESC
            enum:
              - ASC
              - DESC
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              examples:
                Without pagination:
                  value:
                    - id: 0e2f864e-8611-4e41-9d49-1c94b1df5c95
                      title: string
                      content: string
                      status: draft
                      authorId: b1b73593-2445-421a-af42-359114d6c536
                      categoryId: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                      tags:
                        - nestjs
                        - typescript
                        - backend
                      createdAt: 1775299578964
                      updatedAt: 1775299578964
                  description: Without page and limit query parameters
                With pagination:
                  value:
                    total: 1
                    page: 1
                    limit: 10
                    data:
                      - id: 0e2f864e-8611-4e41-9d49-1c94b1df5c95
                        title: string
                        content: string
                        status: draft
                        authorId: b1b73593-2445-421a-af42-359114d6c536
                        categoryId: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                        tags:
                          - nestjs
                          - typescript
                          - backend
                        createdAt: 1775299578964
                        updatedAt: 1775299578964
                  description: With page and limit query parameters
        '400':
          description: Bad request. Wrong query parameters (hacker scope)
      tags:
        - Articles
  /article/{id}:
    get:
      operationId: ArticleController_findOne
      summary: Get single article by id
      description: Get single article by id
      parameters:
        - name: id
          required: true
          in: path
          description: Article id, format UUID v4
          schema: {}
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                id: 0e2f864e-8611-4e41-9d49-1c94b1df5c95
                title: string
                content: string
                status: draft
                authorId: b1b73593-2445-421a-af42-359114d6c536
                categoryId: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                tags:
                  - nestjs
                  - typescript
                  - backend
                createdAt: 1775299578964
                updatedAt: 1775299578964
        '400':
          description: Bad request. Article id is invalid (not uuid)
        '404':
          description: Article not found
      tags:
        - Articles
    put:
      operationId: ArticleController_update
      summary: Update article information
      description: Updates article by ID
      parameters:
        - name: id
          required: true
          in: path
          description: Article id, format UUID v4
          schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateArticleDto'
      responses:
        '200':
          description: The article has been updated
          content:
            application/json:
              example:
                id: 0e2f864e-8611-4e41-9d49-1c94b1df5c95
                title: string
                content: string
                status: draft
                authorId: b1b73593-2445-421a-af42-359114d6c536
                categoryId: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                tags:
                  - nestjs
                  - typescript
                  - backend
                createdAt: 1775299578964
                updatedAt: 1775300238971
        '400':
          description: Bad request. Article id is invalid (not uuid)
        '404':
          description: Article not found
      tags:
        - Articles
    delete:
      operationId: ArticleController_remove
      summary: Deletes article
      description: Deletes article. Deletes all associated comments.
      parameters:
        - name: id
          required: true
          in: path
          description: Article id, format UUID v4
          schema: {}
      responses:
        '204':
          description: The article has been deleted
          example: ''
        '400':
          description: Bad request. Article id is invalid (not uuid)
        '404':
          description: Article not found
      tags:
        - Articles
  /category:
    post:
      operationId: CategoryController_create
      summary: 'Add new category '
      description: 'Adds new category '
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryDto'
      responses:
        '201':
          description: Category is created
          content:
            application/json:
              example:
                id: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                name: string
                description: string
        '400':
          description: Bad request. Body does not contain required fields
      tags:
        - Categories
    get:
      operationId: CategoryController_findAll
      summary: Get all categories
      description: Gets all categories
      parameters:
        - name: page
          required: false
          in: query
          description: Page number (starting from 1)
          schema:
            example: 1
            type: number
        - name: limit
          required: false
          in: query
          description: Number of items per page
          schema:
            example: 10
            type: number
        - name: sortBy
          required: false
          in: query
          description: The field to sort by
          schema:
            example: name
            enum:
              - id
              - name
              - description
            type: string
        - name: order
          required: false
          in: query
          description: Sorting direction
          schema:
            example: DESC
            enum:
              - ASC
              - DESC
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              examples:
                Without pagination:
                  value:
                    - id: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                      name: string
                      description: string
                  description: Without page and limit query parameters
                With pagination:
                  value:
                    total: 1
                    page: 1
                    limit: 10
                    data:
                      - id: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                        name: string
                        description: string
                  description: With page and limit query parameters
        '400':
          description: Bad request. Wrong query parameters (hacker scope)
      tags:
        - Categories
  /category/{id}:
    get:
      operationId: CategoryController_findOne
      summary: Get single category by id
      description: Get single category by id
      parameters:
        - name: id
          required: true
          in: path
          description: Category id, format UUID v4
          schema: {}
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                id: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                name: string
                description: string
        '400':
          description: Bad request. Category id is invalid (not uuid)
        '404':
          description: Category not found
      tags:
        - Categories
    put:
      operationId: CategoryController_update
      summary: Update category information
      description: Updates category information by ID
      parameters:
        - name: id
          required: true
          in: path
          description: Category id, format UUID v4
          schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryDto'
      responses:
        '200':
          description: The category has been updated
          content:
            application/json:
              example:
                id: f3d2f4c6-5376-48df-b4a7-9fe825559db9
                name: string
                description: string
        '400':
          description: Bad request. Category id is invalid (not uuid)
        '404':
          description: Category not found
      tags:
        - Categories
    delete:
      operationId: CategoryController_remove
      summary: Delete category
      description: Deletes category. Sets categoryId to null on associated articles.
      parameters:
        - name: id
          required: true
          in: path
          description: Category id, format UUID v4
          schema: {}
      responses:
        '204':
          description: The category has been deleted
          example: ''
        '400':
          description: Bad request. Category id is invalid (not uuid)
        '404':
          description: Category not found
      tags:
        - Categories
  /comment:
    post:
      operationId: CommentController_create
      summary: Add new comment
      description: Add a comment to an article
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentDto'
      responses:
        '201':
          description: Comment is created
          content:
            application/json:
              example:
                id: 63d364f4-168b-416f-b9d2-865d5a579e87
                content: Great article!
                articleId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                authorId: b1b73593-2445-421a-af42-359114d6c536
                createdAt: 1775287579998
        '400':
          description: Bad request. Body does not contain required fields
        '422':
          description: Unprocessable entity. Referenced articleId doesn't exist
      tags:
        - Comments
    get:
      operationId: CommentController_findAll
      summary: Get comments for an article
      description: >-
        Gets all comments for a specific article. Requires articleId query
        parameter.
      parameters:
        - name: page
          required: false
          in: query
          description: Page number (starting from 1)
          schema:
            example: 1
            type: number
        - name: limit
          required: false
          in: query
          description: Number of items per page
          schema:
            example: 10
            type: number
        - name: articleId
          required: true
          in: query
          description: Article ID to get comments for
          schema:
            example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            type: string
        - name: sortBy
          required: false
          in: query
          description: The field to sort by
          schema:
            example: content
            enum:
              - id
              - content
              - authorId
              - articleId
              - createdAt
            type: string
        - name: order
          required: false
          in: query
          description: Sorting direction
          schema:
            example: DESC
            enum:
              - ASC
              - DESC
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              examples:
                Without pagination:
                  value:
                    - id: 63d364f4-168b-416f-b9d2-865d5a579e87
                      content: Great article!
                      articleId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                      authorId: b1b73593-2445-421a-af42-359114d6c536
                      createdAt: 1775287579998
                  description: Without page and limit query parameters
                With pagination:
                  value:
                    total: 1
                    page: 1
                    limit: 10
                    data:
                      - id: 63d364f4-168b-416f-b9d2-865d5a579e87
                        content: Great article!
                        articleId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                        authorId: b1b73593-2445-421a-af42-359114d6c536
                        createdAt: 1775287579998
                  description: With page and limit query parameters
        '400':
          description: Bad request. Wrong query parameters (hacker scope)
      tags:
        - Comments
  /comment/{id}:
    get:
      operationId: CommentController_findById
      summary: Get single comment by id
      description: Gets single comment by id
      parameters:
        - name: id
          required: true
          in: path
          description: Comment id, format UUID v4
          schema: {}
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                id: 63d364f4-168b-416f-b9d2-865d5a579e87
                content: Great article!
                articleId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                authorId: b1b73593-2445-421a-af42-359114d6c536
                createdAt: 1775287579998
        '400':
          description: Bad request. Comment id is invalid (not uuid)
        '404':
          description: Comment not found
      tags:
        - Comments
    delete:
      operationId: CommentController_remove
      summary: Delete comment
      description: Deletes comment
      parameters:
        - name: id
          required: true
          in: path
          description: Comment id, format UUID v4
          schema: {}
      responses:
        '204':
          description: The comment has been deleted
          example: ''
        '400':
          description: Bad request. Comment id is invalid (not uuid)
        '404':
          description: Comment not found
      tags:
        - Comments
info:
  title: Knowledge Hub
  description: Knowledge hub service for managing articles, categories, and comments
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        login:
          type: string
          example: string
        password:
          type: string
          example: string
        role:
          type: string
          example: admin
      required:
        - login
        - password
    UpdatePasswordDto:
      type: object
      properties:
        oldPassword:
          type: string
          example: string
        newPassword:
          type: string
          example: string
      required:
        - oldPassword
        - newPassword
    CreateArticleDto:
      type: object
      properties:
        title:
          type: string
          example: string
        content:
          type: string
          example: string
        status:
          type: string
          description: Article status
          enum:
            - draft
            - published
            - archived
          example: draft
        authorId:
          type: string
          example: b1b73593-2445-421a-af42-359114d6c536
        categoryId:
          type: string
          example: f3d2f4c6-5376-48df-b4a7-9fe825559db9
        tags:
          description: 'Article tags list '
          example:
            - nestjs
            - typescript
            - backend
          type: array
          items:
            type: string
      required:
        - title
        - content
    UpdateArticleDto:
      type: object
      properties:
        title:
          type: string
          example: string
        content:
          type: string
          example: string
        status:
          type: string
          description: Article status
          enum:
            - draft
            - published
            - archived
          example: draft
        authorId:
          type: string
          example: b1b73593-2445-421a-af42-359114d6c536
        categoryId:
          type: string
          example: f3d2f4c6-5376-48df-b4a7-9fe825559db9
        tags:
          description: 'Article tags list '
          example:
            - nestjs
            - typescript
            - backend
          type: array
          items:
            type: string
    CreateCategoryDto:
      type: object
      properties:
        name:
          type: string
          example: string
        description:
          type: string
          example: string
      required:
        - name
        - description
    UpdateCategoryDto:
      type: object
      properties:
        name:
          type: string
          example: string
        description:
          type: string
          example: string
    CreateCommentDto:
      type: object
      properties:
        content:
          type: string
          example: string
        articleId:
          type: string
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        authorId:
          type: string
          example: b1b73593-2445-421a-af42-359114d6c536
      required:
        - content
        - articleId
        - authorId
